{"name": "test_login", "status": "broken", "statusDetails": {"message": "pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"the login page is open\". Line 4 in scenario \"Successful Login with Valid Credentials\" in the feature \"C:\\Users\\aarti.kyama\\Python_Selenium_Training\\Shanaya_project\\features\\login.feature\"", "trace": "E   pytest_bdd.exceptions.StepDefinitionNotFoundError: Step definition is not found: Given \"the login page is open\". Line 4 in scenario \"Successful Login with Valid Credentials\" in the feature \"C:\\Users\\aarti.kyama\\Python_Selenium_Training\\Shanaya_project\\features\\login.feature\"\nAll traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames."}, "description": "C:/Users//aarti.kyama//Python_Selenium_Training//Shanaya_project//features//login.feature: Successful Login with Valid Credentials", "start": 1738333358325, "stop": 1738333358325, "uuid": "42153b37-c019-4c78-aa6e-0c7288201a15", "historyId": "efa29ea59f3a791c80eebb3dde8a5653", "testCaseId": "efa29ea59f3a791c80eebb3dde8a5653", "fullName": "step_definitions.test_login#test_login", "labels": [{"name": "parentSuite", "value": "step_definitions"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "TIGER02804"}, {"name": "thread", "value": "16956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "step_definitions.test_login"}]}